#%RAML 1.0 Trait

headers:
  client-id:
    description: 
    type: string
    required: true
    example:
      c89220sdsd00222mmld923

  client-secret:
    description: 
    type: string
    required: true
    example:
      jswd77sdd88sd898sdsd0sd    